--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/DeathInventoryLog
build-by-default: true
branches:
- master
projects:
  DeathInventoryLog:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.4.1
        branch: "4.0"
      - src: poggit/libasynql/libasynql
        version: 4.1.0
      - src: SOF3/await-generator/await-generator
        version: ^3.4.2
...
