--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/DeathInventoryLog
build-by-default: true
branches:
- master
projects:
  DeathInventoryLog:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.3
        branch: pm5
      - src: poggit/libasynql/libasynql
        version: ^4.1.1
        branch: pm5
      - src: SOF3/await-generator/await-generator
        version: ^3.4.2
...
