name: DeathInventoryLog
main: muqsit\deathinventorylog\Loader
api: 5.27.0
version: 1.0.1
permissions:
  deathinventorylog.command:
    default: op
commands:
  deathinventorylog:
    aliases: ["dil"]
    permission: deathinventorylog.command