name: DeathInventoryLog
main: muqsit\deathinventorylog\Loader
api: 5.41.0
version: 1.0.4
permissions:
  deathinventorylog.command:
    default: op
commands:
  deathinventorylog:
    aliases: ["dil"]
    permission: deathinventorylog.command